n=int(input('So tien ban dau: '))
k=int(input('So thang gui: '))
T=float(input('Lai suat/thang: '))
m=n*(1+k*T)
print('Voi so tien ban dau',n,end=', ')
print('sau '+str(k)+' thang gui',end=', ')
print('lai suat '+str(T)+'/ thang')
print('Thi so tien nhan duoc cuoi ky la:',m)